### ISSUE TITLE
Provide also raw release contents

### ISSUE THREAD

**Issue by mitar** [anton-yurchenko/go-changelog#4]
I think it would be also useful to provide raw release contents. So all raw lines between one heading and the other. This can then be used to do some custom post-processing if necessary.

**Comment by anton-yurchenko** [comment]
Hello @mitar, 
You should be able to do this by retrieving the desired release ([c.GetRelease("v1.0.0")](https://pkg.go.dev/github.com/anton-yurchenko/go-changelog#:~:text=func%20(c%20*Changelog)-,GetRelease(version%20string)%20*Release,-func%20(c%20*Changelog)) and then formatting it ([r.ToString()](https://pkg.go.dev/github.com/anton-yurchenko/go-changelog#Release.ToString)).
Is that what you are looking for?

***P.S:** you can also do this on the Changelog/Release/Changes level*

**Comment by mitar** [comment]
This reformats the changelog. I was hoping to be able to get something closer to the original formatting.
